changelog:
  categories:
    - title: grid
      labels:
        - 'grid'
      exclude:
        labels:
          - 'release'
          - 'dependencies'
    - title: dependencies
      labels:
        - 'grid'
        - 'dependencies'
