changelog:
  categories:
    - title: core
      labels:
        - 'core'
      exclude:
        labels:
          - 'dependencies'
    - title: dependencies
      labels:
        - 'core'
        - 'dependencies'
