name: Krytenbot

on:
  pull_request:
    types:
      - closed
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - 'core/**'
  issue_comment:
    types:
      - created
      - edited

permissions:
  contents: write
  pull-requests: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  krytenbot:
    name: Krytenbot
    runs-on: ubuntu-latest
    if: (github.event_name == 'pull_request' && github.event.pull_request.merged) || github.event_name == 'push' || github.event_name == 'issue_comment'
    steps:
      - name: Krytenbot
        uses: mbiggs-gresham/krytenbot@dev
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
