name: Krytenbot

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  issue_comment:
    types:
      - created
      - edited

permissions:
  contents: write
  pull-requests: write

jobs:
  krytenbot:
    name: Krytenbot
    runs-on: ubuntu-latest

    steps:
      - name: Krytenbot
        id: Krytenbot
        uses: mbiggs-gresham/krytenbot@dev
        with:
	  app_id: ${{ secrets.APP_ID }}
	  private_key: ${{ secrets.PRIVATE_KEY }}
          token: ${{ secrets.GITHUB_TOKEN }}
