name: Releasebot

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  issue_comment:
    types:
      - created
      - edited

permissions:
  contents: write
  pull-requests: write

jobs:
  releasebot:
    name: Releasebot
    runs-on: ubuntu-latest

    steps:
      - name: Releasebot
        id: Releasebot
        uses: mbiggs-gresham/releasebot@dev
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
